name: Sync to HF Space
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # 혹시 큰 파일이 있을 수 있으니 추가하면 좋습니다.
      - name: Push to HF
        run: |
          git remote add hf https://sungsull:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/sungsull/cooker
          git push hf main --force